### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by lion-jg** [lion-jg/furima-28838#9]
### URL
https://furima-28838.herokuapp.com/
　　
### Basic認証のIDとパスワード
ID:admin
password:2222
　　
### 出品者用のメールアドレスとパスワード

- 太郎
mail : 000@gmail.com
password : 000ooo
　　
### 購入者用のメールアドレスとパスワード

- 花子
mail : 111@gmail.com
password : 111qqq
　　
### 購入用カードの番号・期限・セキュリティコード
カード番号：4242424242424242
期限：いつでもOK
セキュリティコード：123

**Comment by rumaruma0408** [comment]
lion-jgさん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
